name: Trigger auto deployment for container-app-m264uydg43wxy

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/container-app-m264uydg43wxy-AutoDeployTrigger-80c215c3-1300-4352-b538-4a715e312c01.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPM264UYDG43WXY_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPM264UYDG43WXY_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPM264UYDG43WXY_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPM264UYDG43WXY_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPM264UYDG43WXY_REGISTRY_PASSWORD }}
          containerAppName: container-app-m264uydg43wxy
          resourceGroup: expresssample8ef1ad13
          imageToBuild: default/container-app-m264uydg43wxy:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


